name: Deploy

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]
    
    - name: hello
      run: echo hello

    - name: Setup doc deploy
      run: |
        git config --global user.name "actions docs deployer"
        git config --global user.email docs@github-actions.dummy.com

    - name: Build and deploy docs
      run: |
        mike deploy --update-aliases --push --remote origin ${{ github.ref_name }} latest
